### ISSUE TITLE
Metodo createPoll in PollController

### ISSUE THREAD

**Issue by PZirp** [protti/UnisaBeVoyager#10]
Il metodo ha questa firma:

_public static Poll createPoll(String description,int pos, int neg,  GregorianCalendar startDate, GregorianCalendar endDate,int travelId)_

Perchè se sto CREANDO un sondaggio gli devo passare il numero di voti positi e negativi, che non esistino ancora?

Stessa cosa per i costruttori:

_public Poll(String description, int vnegative, int vpositive, GregorianCalendar startDate, GregorianCalendar endDate)_

_public Poll(int id, String description, int vnegative, int vpositive, GregorianCalendar startDate, GregorianCalendar endDate)_

**Comment by protti** [comment]
Effettivamente dovrebbero essere tolti tali parametri, ed inizializzarli direttamente all'interno del costruttore

**Comment by alexlon994** [comment]
In realtà ritengo che, per rendere il codice più leggibile, ogni oggetto dovrebbe avere un costruttore vuoto, e poi andare a settare tutti i parametri tramite metodi setter. Utilizzare il costruttore con i parametri può confondere parecchio le idee in quanto i parametri da inserire sono molti, e quindi anche due stringhe potrebbero essere confuse. Questa è solo una scelta implementativa, potremmo fare anche i costruttori con i parametri, però sembra migliore l'utilizzo dei setter, almeno per me.

**Comment by protti** [comment]
Paolo un costruttore con vpositive e vnegative ci serve per quando una query ci restituisce un Poll ed abbiamo bisogno di instanziarlo

**Comment by PZirp** [comment]
Issue risolta
