### ISSUE TITLE
Metodo checkUserTravel in UserManager

### ISSUE THREAD

**Issue by PZirp** [protti/UnisaBeVoyager#12]
Immagino che checkUserTravel serva per vedere se un utente ha partecipato ad un viaggio. Questo lo dovremmo usare quando un utente vuole dare un feedback ad un itinerario. Ok, quello che ci serve però è sapere se l'utente ha partecipato ad un viaggio che USA quell'itinerario. Il metodo così com'è ora controlla solo se ha partecipato ad un viaggio, senza guardare l'itinerario, ed è inutile.

Il caso d'uso è Dare feedback ad un itinerario

Rinominalo anche in checkUserPartecipation, secondo il sequence

**Comment by PZirp** [comment]
Ok checkUserTravel serve per controllare se un utente ha partecipato ad un viaggio con un altro utente (per dare il feedback all'utente), fatto sta che manca proprio il metodo per fare quello di cui sopra.

**Comment by alexlon994** [comment]
C'è già. L'ho messo in TravelManager, però si chiama checkUserPartecipant. Lo devo spostare in UserManager?
