### ISSUE TITLE
metodo checkUserTravel non fa quello che dovrebbe

### ISSUE THREAD

**Issue by PZirp** [protti/UnisaBeVoyager#13]
checkUserTravel ci serve per sapere se un utente ha partecipato ad un viaggio a cui ha partecipato un altro utente, per dare il feedback a quest'ultimo.

Solo che checkUserTravel controlla se un utente ha partecipato ad un viaggio, e mi restituisce un booleano. E basta.

Allora... Per prima cosa, il metodo deve prende due id di due utenti, e poi controlla se hanno viaggi in comune.

Poi a questo punto direi di rinominarlo in "checkUserHasTraveledWith" per essere più chiari su a cosa serve.

**Comment by alexlon994** [comment]
Ho fatto il metodo checkUserHasTraveledWith, solo che non ho capito se il metodo checkUserTravel intendi eliminarlo
