### ISSUE TITLE
E possibile creare un itinerario senza luoghi

### ISSUE THREAD

**Issue by PZirp** [protti/UnisaBeVoyager#18]
Se tento di creare un itinerario inserendo nome e descrizione, ma senza aggiungere alcun luogo, il viaggio viene creato senza errori. Dovrebbe essere impossibile una condizone del genere.

**Comment by alexlon994** [comment]
Questo perchè viene passata una lista vuota però si sta controllando se la lista è null, ho risolto semplicemente controllando solo se la lista è vuota.
