### ISSUE TITLE
E' possibile creare un viaggio senza itinerario in un caso particolare

### ISSUE THREAD

**Issue by PZirp** [protti/UnisaBeVoyager#20]
Se eseguo queste operazioni in sequenza:

1) Tento di creare un viaggio
2) Scelgo l'itinerario e lo seleziono, ma non inserisco gli altri dati
3) Faccio crea itinerario. Mi da errore come dovrebbe fino a qui
4) Tento di creare un nuovo itinerario
5) Inserisco tutti i dati ma non l'itinerario
6) Clicco crea, il viaggio viene creato senza itinerario selezionato

Evidentemente rimane salvato quello precedente nella sessione quando capita un errore, andrebbe rimosso

**Comment by alexlon994** [comment]
Si in pratica nella servlet utilizzata per creare un viaggio l'itinerario viene rimosso dalla sessione solo quando il viaggio viene perfettamente creato, ma non quando si verifica un errore. Bisogna rimuovere l'itinerario dalla sessione anche in caso di errore su dati mancanti.
