### ISSUE TITLE
Gestione viaggi e feedback

### ISSUE THREAD

**Issue by PZirp** [protti/UnisaBeVoyager#9]
I viaggi, intesi come oggetti che hanno data d'inizio, fine, ed un itinerario, una volta conclusi, come vanno gestiti?

- Un viaggio creato da un TourOperator può riceve dei feedback, ma il TourOperator specifica anche una data di inizio e fine? Vuol dire che il viaggio creato dal TourOperator ha una scadenza e poi non è più accessibile? Oppure il TourOperator specifica solo l'itinerario, poi le date sono scelte dall'utente?

- Un viaggi concluso, come avevamo proposto, può ricevere dei feedback, ma non vi si può più partecipare. Il viaggio rimane comunque visibile sul sito ma non è interagibile? Se così fosse a cosa serve dare un feedback, dato che comunque sarebbe dato solo da poche persone?  
Mi sembrerebbe più logico dare il feedback all'itinerario, dando la possibilità di selezionarlo ed aggiungerlo ad un viaggio, in modo tale che quando il viaggio finisce, l'itinerario comunque rimane sul database ed è accessibile

**Comment by protti** [comment]
1)Il TourOperator potrebbe dare un margine di tempo in cui la sua offerta è attiva, nel senso, alcuni coupon che egli potrà inserire nel pacchetto (Coupon che verranno acquistati dagli utenti, quindi il TourOperator li proporrà solamente) hanno una scadenza dalla pubblicazione sul sito di tali, quindi una sorta di lasso di tempo dovrà comunque esserci, e quindi, dato che vi sarà l'inutilizzo dei coupon, mi sembra inutile porlo come accessibile.

**Comment by protti** [comment]
2) Essendo l'itinerario solo un insieme di luoghi, non mi sembra corretto caricarlo anche di un'altra responsabilità, come quella del feedback, quindi, essendo il viaggio un luogo in cui è presente tale itinerario, sembrerebbe più corretto che il feedback venga dato a quest ultimo. Ovviamente da viaggio potrebbe essere utile avere una operazione che ti restituisca l'itinerario associato, e che quindi permetterebbe il riutilizzo di tale.

**Comment by MrRuggiero** [comment]
1) Nel caso del viaggio proposto dal tour operator, conviene che come il viaggio di un utente normale, anche questo abbia data di inizio e fine decisa dal tour operator in modo talabda avere maggiore conformità.
2) Su questo punto sono d'accordo con donato in quanto un itinerario, a differenza del viaggio non scade, quindi potrà essere richiamato dall'utente o al massimo dare una scadenza più lunga all'itinerario rispetto al viaggio.

**Comment by alexlon994** [comment]
1) Sono d'accordo con Salvatore, penso che sia lo stesso dell'utente normale, con la differenza che al TourOperator, ogni volta che un utente partecipa al viaggio, viene versata un certo tot in denaro.
2) Su questo punto sono d'accordo con Zirpoli invece, è molto meglio dare il feedback ad un itinerario, se questo può essere visto da persone esterne. Il viaggio è una questione privata tra gli organizzatori.

**Comment by TheJoin95** [comment]
Nota: se la pagina di un viaggio è visibile a tutti, perciò indicizzata sui motori di ricerca, è bene non restituire un 404 poiché potrebbe inficiare sull'indicizzazione del sito stesso.

Se un viaggio/itinerario pubblico è concluso, sarebbe meglio (a mio modo di vedere e in base a delle regole seo) inserire una nota di "viaggio concluso" e lasciare la pagina accessibile.
